from .dashboard import DashboardPage
from .products import ProductsPage
from .customers import CustomersPage
from .sales import SalesPage
from .sales_reports import SalesReportPage
from .daily_profit import DailyProfitPage
from .monthly_profit import  MonthlyProfitPage
from .settings import SettingsPage
from .purchase import PurchasePage
from .dues import DuesPage
from .expenses import ExpensesPage
from .inventory import InventoryPage